# Generated by Django 3.0.6 on 2020-10-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtask', '0002_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
