# Generated by Django 3.0.6 on 2020-10-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testtask', '0003_likeanalytic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeAnalytic',
            new_name='LikeAnalytics',
        ),
    ]
